# Generated by Django 5.2.5 on 2026-02-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in Kobo (₦1000 = 100000)'),
        ),
    ]
