# Generated by Django 5.2.5 on 2026-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tier_name',
            field=models.CharField(default='basic', max_length=50),
        ),
    ]
