# Generated by Django 5.2.5 on 2026-07-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_school_tier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='subject_teacher_pin',
            field=models.CharField(blank=True, help_text='Unique PIN for Subject Teachers to log in', max_length=20, null=True, unique=True),
        ),
    ]
