# Generated by Django 5.2.5 on 2026-07-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_assignment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(help_text="e.g., 'Subject Teacher' or specific user", max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_range', models.CharField(blank=True, help_text='e.g. 4-20', max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('questions', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_uploads', to='score.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
