# Generated by Django 5.2.5 on 2026-07-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_materialupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialupload',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
