# Generated by Django 5.2.5 on 2025-12-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersmatters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hire',
            options={'ordering': ['-date_hired']},
        ),
        migrations.AlterField(
            model_name='employer',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='sname',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires_made', to='teachersmatters.employer'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='teachersmatters.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hired',
            field=models.BooleanField(default=False, verbose_name='Currently Hired'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sname',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
        migrations.AlterUniqueTogether(
            name='hire',
            unique_together={('teacher', 'employer')},
        ),
    ]
