# Generated by Django 5.2.5 on 2025-12-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersmatters', '0002_alter_hire_options_alter_employer_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='date_unhired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='unhired_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
