# Generated by Django 5.2.5 on 2025-12-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachersmatters', '0003_hire_date_unhired_hire_unhired_by_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hire',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='hired',
        ),
    ]
