"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths: settings/base.py -> parent.parent = school package root.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!q92qxfibhjx4j1__n=&vtc#^!tt$*84ohic=gm5=71o2$38s)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Tier modules (basic/pro/premium) override this; allow localhost for dev.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'score',
    'teachersmatters',
    'exams',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'score.middleware.SessionCookieInjectMiddleware',  # Before SessionMiddleware: pick role-specific session cookie
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Session cookie path scope: teacher vs student tabs use different cookies (avoids cross-tab overwrite & CSRF)
    'score.middleware.SessionCookiePathMiddleware',
    # ✅ School Authentication Middleware - must be AFTER SessionMiddleware and AuthenticationMiddleware
    'score.middleware.SchoolAuthenticationMiddleware',
]

ROOT_URLCONF = 'school.urls'

WSGI_APPLICATION = 'school.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'score.context_processors.tier_info',
                'score.context_processors.available_features',
                'score.context_processors.school_setting',
            ],
        },
    },
]

# This loads the variables from your .env file into Python
load_dotenv(BASE_DIR / '.env')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==================================================
# EMAIL CONFIGURATION
# ==================================================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "asemakahamande01@gmail.com"
EMAIL_HOST_PASSWORD = "gnhracyswxdfddhb"
DEFAULT_FROM_EMAIL = "Termly Report Card <asemakahamande01@gmail.com>"
SERVER_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = "asemakahamande01@gmail.com"


# ==================================================
# PAYSTACK PAYMENT CONFIGURATION
# ==================================================
# Read from .env (live keys). Fallback to test keys only when env vars are unset or empty.
_default_secret = "sk_live_245989366322524defc076a98b6ae9ccdd3d6a3b"
_default_public = "pk_live_958d2a42794baf8386f154a0eeeab3558dbf55d3"
PAYSTACK_SECRET_KEY = (os.getenv("PAYSTACK_SECRET_KEY") or _default_secret).strip()
PAYSTACK_PUBLIC_KEY = (os.getenv("PAYSTACK_PUBLIC_KEY") or _default_public).strip()
PAYSTACK_BASE_URL = (os.getenv("PAYSTACK_BASE_URL") or "https://api.paystack.co").strip()

# Production: set SECRET_KEY and Paystack live keys in your host's env (e.g. Render
# Dashboard → Environment). Build may load settings before env is available, so we
# don't raise here; use strong SECRET_KEY and sk_live_/pk_live_ in production.


# ==================================================
# AUTHENTICATION & SESSION CONFIGURATION
# ==================================================
# Redirect to custom login view (not Django's default)
LOGIN_URL = '/login/'

# Session settings for school authentication
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store sessions in database
SESSION_COOKIE_AGE = 86400  # 24 hours (adjust as needed)
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_NAME = 'schoolsessionid'  # Custom session cookie name


# ==================================================
# SECURITY SETTINGS
# ==================================================
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS protection

# Development: no HTTPS redirect (set True only in production with HTTPS)
SECURE_SSL_REDIRECT = False

# ==================================================
# LOGGING CONFIGURATION (Optional but Recommended)
# ==================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'school_access.log',
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'score': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)


# ==================================================
# CUSTOM SETTINGS FOR SCHOOL MANAGEMENT
# ==================================================

# Maximum file upload size (adjust as needed)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# Allowed file extensions for uploads
ALLOWED_UPLOAD_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.pdf', '.doc', '.docx']

# Maximum number of students per school (for billing purposes)
MAX_STUDENTS_PER_SCHOOL = 10000

# Pin pricing (in Naira)
# PIN_PRICE_PER_STUDENT = 200

# Session timeout warning (in seconds)
SESSION_TIMEOUT_WARNING = 300  # 5 minutes before expiry


# ==================================================
# NOTES FOR PRODUCTION DEPLOYMENT
# ==================================================
"""
BEFORE DEPLOYING TO PRODUCTION:
1. Change DEBUG to False
2. Set proper ALLOWED_HOSTS
3. Use environment variables for sensitive data (SECRET_KEY, DB, EMAIL_HOST_PASSWORD, PAYSTACK_*)
4. Enable HTTPS security settings (SECURE_SSL_REDIRECT, SESSION_COOKIE_SECURE, etc.)
5. python manage.py check --deploy
6. python manage.py collectstatic --noinput
"""
